-- source: liquibase liquibase/2.1.x.x/client_notifications.xml::4::csteele
-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS clinlims.ozekimessageout (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender VARCHAR(30), receiver VARCHAR(30), msg VARCHAR(160), senttime VARCHAR(100), receivedtime VARCHAR(100), operator VARCHAR(100), msgtype VARCHAR(30), preference VARCHAR(30), status VARCHAR(100), errormsg VARCHAR(250), CONSTRAINT ozekimessageout_pkey PRIMARY KEY (id));
CREATE INDEX IF NOT EXISTS idx_ozekimessageout_id ON clinlims.ozekimessageout(id);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.1.x.x/client_notifications.xml::4::csteele
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
