-- source: liquibase liquibase/2.6.x.x/add_lab_roles_map_table.xml::2::mosesmutesa
-- +goose Up
-- +goose StatementBegin
-- Creating lab_unit_role_map table
CREATE TABLE IF NOT EXISTS lab_unit_role_map (lab_unit_role_map_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, lab_unit VARCHAR(64) NOT NULL, CONSTRAINT lab_unit_role_map_pkey PRIMARY KEY (lab_unit_role_map_id));
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS lab_unit_role_map;
-- +goose StatementEnd
