-- source: liquibase liquibase/2.6.x.x/method.xml::3::cliff
-- +goose Up
-- +goose StatementBegin
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'EIA', NOW(), 'Enzyme-linked immunoassay', 'EIA', 'Y', '2007-04-24 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'EIA')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'PCR', NOW(), 'Polymerase Chain Reaction', '', 'Y', '2006-09-18 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'PCR')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'STAIN', NOW(), 'Stain', '', 'Y', '2006-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'STAIN')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'CULTURE', NOW(), 'Culture', '', 'N', '2006-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'CULTURE')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'PROBE', NOW(), 'Probe', '', 'Y', '2006-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'PROBE')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'BIOCHEMICAL', NOW(), 'Biochemical', '', 'Y', '2006-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'BIOCHEMICAL')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'Diane Test', NOW(), 'Diane Test', '', 'Y', '2006-09-06 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'Diane Test')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'HPLC', NOW(), 'High Pressure Liquid Chromatography', '', 'Y', '2006-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'HPLC')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'DNA SEQUENCING', NOW(), 'DNA Sequencing', '', 'Y', '2006-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'DNA SEQUENCING')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'AUTO', NOW(), 'Automated (Haiti)', '', 'Y', '2006-09-24 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'AUTO')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'MANUAL', NOW(), 'test done manually (Haiti)', '', 'Y', '2009-09-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'MANUAL')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'HIV_TEST_KIT', NOW(), 'Uses Hiv test kit', '', 'Y', '2009-09-30 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'HIV_TEST_KIT')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.method (id, name, lastupdated, description, reporting_description, is_active, active_begin, active_end, name_localization_id) VALUES (nextval('clinlims.method_seq'), 'SYPHILIS_TEST_KIT', NOW(), 'Test kit for syphilis', '', 'Y', '2009-10-29 00:00:00', NULL, (SELECT id FROM clinlims.localization WHERE english = 'SYPHILIS_TEST_KIT')) ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.6.x.x/method.xml::3::cliff
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
