-- source: liquibase liquibase/2.6.x.x/add_retroci_sampletype_test_element.xml::202208313::CIV developer Group
-- +goose Up
-- +goose StatementBegin
-- Add elements to map retroci tests to sampletype 'EDTA Tube'
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'CD4')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Génotypage')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Viral Load')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'DNA PCR')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'GB')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'PLQ')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Neut %')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Lymph %')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Mono %')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Eo %')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Baso %')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'HCT')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'CCMH')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'GR')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'Hb')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'VGM')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'TCMH')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'CD3 percentage count')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'CD4 percentage count')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'CD4 absolute count')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'NE#')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'MO#')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'BA#')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'LY#')) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES (nextval('clinlims.sample_type_test_seq'), (SELECT id FROM clinlims.type_of_sample WHERE description = 'EDTA Tube'), (SELECT id FROM clinlims.test WHERE description = 'EO#')) ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.6.x.x/add_retroci_sampletype_test_element.xml::202208313::CIV developer Group
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
