-- source: liquibase liquibase/2.7.x.x/add_tb_tests.xml::2023091801::CIV developer Group
-- +goose Up
-- +goose StatementBegin
INSERT INTO clinlims.localization(id, description, english,french, lastupdated) VALUES
            (nextval('localization_seq'),'test name','GeneXpert MTB/RIF','GeneXpert MTB/RIF',now()),
            (nextval('localization_seq'),'test name','TB LAMP','TB LAMP',now()),
            (nextval('localization_seq'),'test name','Auramine bacilloscopy','Bacilloscopie Auramine',now()),
            (nextval('localization_seq'),'test name','Bacilloscopie Ziehl-Neelsen','Bacilloscopie Ziehl-Neelsen',	now()),
            (nextval('localization_seq'),'test name','Culture Milieu LJ','Culture Milieu LJ',now()),
            (nextval('localization_seq'),'test name','Culture Milieu MGIT','Culture Milieu MGIT',now()),
            (nextval('localization_seq'),'panel name','MTBDRplus','MTBDRplus',now()),
            (nextval('localization_seq'),'panel name','MTBDRsl','MTBDRsl',now()),
            (nextval('localization_seq'),'test name','Rifampicine','Rifampicine',now()),
            (nextval('localization_seq'),'test name','Isoniazide','Isoniazide',now()),
            (nextval('localization_seq'),'test name','Fluoroquinolone','Fluoroquinolone',now()),
            (nextval('localization_seq'),'test name','Injectable','Injectable',now()),
            (nextval('localization_seq'),'panel name','Antibiogram TB 1st Line','Antibiogramme TB 1ere Ligne',now()),
            (nextval('localization_seq'),'panel name','Antibiogram TB 2nd Line','Antibiogramme TB 2e Ligne',now()),
            (nextval('localization_seq'),'test name','Pyrazinamide','Pyrazinamide',now()),
            (nextval('localization_seq'),'test name','Ethambutol','Ethambutol',now()),
            (nextval('localization_seq'),'test name','Capreomicine','Capreomicine',now()),
            (nextval('localization_seq'),'test name','Teridizone','Teridizone',now()),
            (nextval('localization_seq'),'test name','Kanamycine','Kanamycine',now()),
            (nextval('localization_seq'),'test name','Imipenem','Imipenem',now()),
            (nextval('localization_seq'),'test name','Streptomicine','Streptomicine',now()),
            (nextval('localization_seq'),'test name','Ethionamide','Ethionamide',now()),
            (nextval('localization_seq'),'test name','Prothionamide','Prothionamide',now()),
            (nextval('localization_seq'),'test name','Cyclosérine','Cyclosérine',now()),
            (nextval('localization_seq'),'test name','Linezolid','Linezolid',now()),
            (nextval('localization_seq'),'test name','Moxifloxacine','Moxifloxacine',now()),
            (nextval('localization_seq'),'test name','Clofazimine','Clofazimine',now()),
            (nextval('localization_seq'),'test name','Levofloxacine','Levofloxacine',now()),
            (nextval('localization_seq'),'test name','PAS','PAS',now()),
            (nextval('localization_seq'),'test name','Imipénème-Cilastatine','Imipénème-Cilastatine',now()),
            (nextval('localization_seq'),'test name','Meropenem','Meropenem',now()),
            (nextval('localization_seq'),'test name','Bedaquilline','Bedaquilline',now()),
            (nextval('localization_seq'),'test name','Delamanide','Delamanide',now()),
            (nextval('localization_seq'),'test name','TB LAM urinaire','TB LAM urinaire',now()),
            (nextval('localization_seq'),'test report name','GeneXpert MTB/RIF','GeneXpert MTB/RIF',now()),
            (nextval('localization_seq'),'test report name','TB LAMP','TB LAMP',now()),
            (nextval('localization_seq'),'test report name','Auramine bacilloscopy','Bacilloscopie Auramine',now()),
            (nextval('localization_seq'),'test report name','Bacilloscopie Ziehl-Neelsen','Bacilloscopie Ziehl-Neelsen',	now()),
            (nextval('localization_seq'),'test report name','Culture Milieu LJ','Culture Milieu LJ',now()),
            (nextval('localization_seq'),'test report name','Culture Milieu MGIT','Culture Milieu MGIT',now()),
            (nextval('localization_seq'),'test report name','Rifampicine','Rifampicine',now()),
            (nextval('localization_seq'),'test report name','Isoniazide','Isoniazide',now()),
            (nextval('localization_seq'),'test report name','Fluoroquinolone','Fluoroquinolone',now()),
            (nextval('localization_seq'),'test report name','Injectable','Injectable',now()),
            (nextval('localization_seq'),'test report name','Pyrazinamide','Pyrazinamide',now()),
            (nextval('localization_seq'),'test report name','Ethambutol','Ethambutol',now()),
            (nextval('localization_seq'),'test report name','Capreomicine','Capreomicine',now()),
            (nextval('localization_seq'),'test report name','Teridizone','Teridizone',now()),
            (nextval('localization_seq'),'test report name','Kanamycine','Kanamycine',now()),
            (nextval('localization_seq'),'test report name','Imipenem','Imipenem',now()),
            (nextval('localization_seq'),'test report name','Streptomicine','Streptomicine',now()),
            (nextval('localization_seq'),'test report name','Ethionamide','Ethionamide',now()),
            (nextval('localization_seq'),'test report name','Prothionamide','Prothionamide',now()),
            (nextval('localization_seq'),'test report name','Cyclosérine','Cyclosérine',now()),
            (nextval('localization_seq'),'test report name','Linezolid','Linezolid',now()),
            (nextval('localization_seq'),'test report name','Moxifloxacine','Moxifloxacine',now()),
            (nextval('localization_seq'),'test report name','Clofazimine','Clofazimine',now()),
            (nextval('localization_seq'),'test report name','Levofloxacine','Levofloxacine',now()),
            (nextval('localization_seq'),'test report name','PAS','PAS',now()),
            (nextval('localization_seq'),'test report name','Imipénème-Cilastatine','Imipénème-Cilastatine',now()),
            (nextval('localization_seq'),'test report name','Meropenem','Meropenem',now()),
            (nextval('localization_seq'),'test report name','Bedaquilline','Bedaquilline',now()),
            (nextval('localization_seq'),'test report name','Delamanide','Delamanide',now()),
            (nextval('localization_seq'),'test report name','TB LAM urinaire','TB LAM urinaire',now()) ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.7.x.x/add_tb_tests.xml::2023091801::CIV developer Group
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
