-- source: liquibase liquibase/2.7.x.x/add_tb_tests.xml::2023091803::CIV developer Group
-- +goose Up
-- +goose StatementBegin
INSERT INTO clinlims.test(id, method_id, uom_id, description,loinc, reporting_description,sticker_req_flag, is_active,active_begin, active_end, is_reportable,
            time_holding, time_wait,time_ta_average, time_ta_warning,time_ta_max, label_qty, lastupdated,label_id, test_trailer_id,test_section_id, scriptlet_id,
            test_format_id, local_code,	sort_order, name, orderable,guid,name_localization_id, reporting_name_localization_id,default_test_result_id, notify_results)
            VALUES
            (nextval('test_seq'),null,null,'GeneXpert MTB/RIF','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'GeneXpert MTB/RIF',1,'GeneXpert MTB/RIF','t','c9413e2e-8979-440f-9673-6bf1ddc73f6f',
            (select id	from localization where description = 'test name' and french = 'GeneXpert MTB/RIF' limit 1),
            (select id from localization where	description = 'test report name' and french = 'GeneXpert MTB/RIF' limit 1),	null,'f'),
            (nextval('test_seq'),null,null,'TB LAMP','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'TB LAMP',1,'TB LAMP','t','837e42e0-e9a1-45dd-b89d-2e764553448b',
            (select id	from localization where description = 'test name' and french = 'TB LAMP' limit 1),
            (select id from localization where	description = 'test report name' and french = 'TB LAMP' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Bacilloscopie Auramine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Bacilloscopie Auramine',1,'Bacilloscopie Auramine','t','e4543638-81c2-4a14-95a2-fe706d321b21',
            (select id	from localization where description = 'test name' and french = 'Bacilloscopie Auramine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Bacilloscopie Auramine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Bacilloscopie Ziehl-Neelsen','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Bacilloscopie Ziehl-Neelsen',1,'Bacilloscopie Ziehl-Neelsen','t','1ee24887-4c74-460f-8eb3-4aed3a323a2d',
            (select id	from localization where description = 'test name' and french = 'Bacilloscopie Ziehl-Neelsen' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Bacilloscopie Ziehl-Neelsen' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Culture Milieu LJ','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Culture Milieu LJ',1,'Culture Milieu LJ','t','b0373870-04d7-4a55-92f5-eed1e2fc3935',
            (select id	from localization where description = 'test name' and french = 'Culture Milieu LJ' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Culture Milieu LJ' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Culture Milieu MGIT','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Culture Milieu MGIT',1,'Culture Milieu MGIT','t','1043ff93-ca92-4123-87d9-bc63dc4cb8fb',
            (select id	from localization where description = 'test name' and french = 'Culture Milieu MGIT' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Culture Milieu MGIT' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Rifampicine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Rifampicine',1,'Rifampicine','t','b026e596-9455-45d1-bb1e-701826855338',
            (select id	from localization where description = 'test name' and french = 'Rifampicine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Rifampicine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Isoniazide','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Isoniazide',1,'Isoniazide','t','34a8ded2-3418-4410-88a1-6b61639aab54',
            (select id	from localization where description = 'test name' and french = 'Isoniazide' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Isoniazide' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Fluoroquinolone','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Fluoroquinolone',1,'Fluoroquinolone','t','b7a92712-0d6c-4c62-b516-4e2c5aa9db15',
            (select id	from localization where description = 'test name' and french = 'Fluoroquinolone' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Fluoroquinolone' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Injectable','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Injectable',1,'Injectable','t','02c088d2-20a0-4c5d-8a38-eda89876a6c0',
            (select id	from localization where description = 'test name' and french = 'Injectable' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Injectable' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Pyrazinamide','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Pyrazinamide',1,'Pyrazinamide','t','a82f3b98-6a7e-4884-bb91-c4a174ce3f72',
            (select id	from localization where description = 'test name' and french = 'Pyrazinamide' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Pyrazinamide' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Ethambutol','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Ethambutol',1,'Ethambutol','t','b115cb58-511d-41d1-8212-d6d88053b9e2',
            (select id	from localization where description = 'test name' and french = 'Ethambutol' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Ethambutol' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Capreomicine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Capreomicine',1,'Capreomicine','t','89d4e974-ae49-4b93-8906-98b579a86f69',
            (select id	from localization where description = 'test name' and french = 'Capreomicine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Capreomicine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Teridizone','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Teridizone',1,'Teridizone','t','5d56f762-ca73-485e-92fc-6fd035cacd8e',
            (select id	from localization where description = 'test name' and french = 'Teridizone' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Teridizone' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Kanamycine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Kanamycine',1,'Kanamycine','t','5354866f-64b0-43a9-a414-e168418db871',
            (select id	from localization where description = 'test name' and french = 'Kanamycine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Kanamycine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Imipenem','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Imipenem',1,'Imipenem','t','077ea0ca-d075-49f9-a33d-5a0e891efb71',
            (select id	from localization where description = 'test name' and french = 'Imipenem' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Imipenem' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Streptomicine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Streptomicine',1,'Streptomicine','t','f248174d-84b2-4ec1-8ebe-528ec62c210d',
            (select id	from localization where description = 'test name' and french = 'Streptomicine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Streptomicine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Ethionamide','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Ethionamide',1,'Ethionamide','t','95a8a513-c3de-4caf-b9e3-f2abc20281c7',
            (select id	from localization where description = 'test name' and french = 'Ethionamide' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Ethionamide' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Prothionamide','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Prothionamide',1,'Prothionamide','t','47b7255c-3d7e-4d22-a37e-723667a5daef',
            (select id	from localization where description = 'test name' and french = 'Prothionamide' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Prothionamide' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Cyclosérine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Cyclosérine',1,'Cyclosérine','t','020d39d0-5eec-4ca9-bcc9-4a1031d1e339',
            (select id	from localization where description = 'test name' and french = 'Cyclosérine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Cyclosérine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Linezolid','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Linezolid',1,'Linezolid','t','7681ae7b-f62c-4480-a83b-18a008d336e2',
            (select id	from localization where description = 'test name' and french = 'Linezolid' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Linezolid' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Moxifloxacine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Moxifloxacine',1,'Moxifloxacine','t','b10587c8-d3b5-486c-bac2-8d07c62144d7',
            (select id	from localization where description = 'test name' and french = 'Moxifloxacine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Moxifloxacine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Clofazimine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Clofazimine',1,'Clofazimine','t','6834169e-c1d2-49ba-9272-34d4fda0519e',
            (select id	from localization where description = 'test name' and french = 'Clofazimine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Clofazimine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Levofloxacine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Levofloxacine',1,'Levofloxacine','t','5bf4b52c-52b8-4164-b634-c57e22a0f4eb',
            (select id	from localization where description = 'test name' and french = 'Levofloxacine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Levofloxacine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'PAS','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'PAS',1,'PAS','t','4a2941a2-0997-4538-89e0-5a7e4fcb14de',
            (select id	from localization where description = 'test name' and french = 'PAS' limit 1),
            (select id from localization where	description = 'test report name' and french = 'PAS' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Imipénème-Cilastatine','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Imipénème-Cilastatine',1,'Imipénème-Cilastatine','t','b33a435c-d884-4c80-a324-dffd4a289697',
            (select id	from localization where description = 'test name' and french = 'Imipénème-Cilastatine' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Imipénème-Cilastatine' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Meropenem','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Meropenem',1,'Meropenem','t','4fe3dcf0-ea96-4523-b530-1cf3f116871c',
            (select id	from localization where description = 'test name' and french = 'Meropenem' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Meropenem' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Bedaquilline','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Bedaquilline',1,'Bedaquilline','t','1498e2db-4114-4489-b378-27e7710fbdf3',
            (select id	from localization where description = 'test name' and french = 'Bedaquilline' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Bedaquilline' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'Delamanide','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'Delamanide',1,'Delamanide','t','a66669e6-27dc-4895-9b5e-981151b00f3a',
            (select id	from localization where description = 'test name' and french = 'Delamanide' limit 1),
            (select id from localization where	description = 'test report name' and french = 'Delamanide' limit 1),null,'f'),
            (nextval('test_seq'),null,null,'TB LAM urinaire','',null,null,'Y',null,null,'N',null,null,null,null,null,null,now(),null,null,
            (select id	from test_section where name = 'TB' limit 1),
            null,null,'TB LAM urinaire',1,'TB LAM urinaire','t','f41361dc-1c51-4684-a42d-5ec34435a387',
            (select id	from localization where description = 'test name' and french = 'TB LAM urinaire' limit 1),
            (select id from localization where	description = 'test report name' and french = 'TB LAM urinaire' limit 1),null,'f') ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.7.x.x/add_tb_tests.xml::2023091803::CIV developer Group
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
