-- source: liquibase liquibase/2.7.x.x/add_tb_tests.xml::2023091815::CIV developer Group
-- +goose Up
-- +goose StatementBegin
INSERT INTO clinlims.result_limits(id, test_id,	test_result_type_id,min_age, max_age, gender, low_normal,
            high_normal, low_valid,	high_valid, lastupdated, normal_dictionary_id,	always_validate)
            VALUES
            (nextval('result_limits_seq'),(select id from test where description = 'GeneXpert MTB/RIF'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'TB LAMP'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Bacilloscopie Auramine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Bacilloscopie Ziehl-Neelsen'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Culture Milieu LJ'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Culture Milieu MGIT'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Rifampicine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Isoniazide'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Fluoroquinolone'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Injectable'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Pyrazinamide'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Ethambutol'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Capreomicine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Teridizone'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Kanamycine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Imipenem'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Streptomicine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Ethionamide'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Prothionamide'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Cyclosérine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Cyclosérine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Linezolid'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Moxifloxacine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Clofazimine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Levofloxacine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'PAS'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Imipénème-Cilastatine'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Meropenem'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Meropenem'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Bedaquilline'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'Delamanide'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f'),
            (nextval('result_limits_seq'),(select id from test where description = 'TB LAM urinaire'),
            2,0,'Infinity',null,'-Infinity','Infinity','-Infinity','Infinity',now(),null,'f') ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.7.x.x/add_tb_tests.xml::2023091815::CIV developer Group
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
