-- source: liquibase liquibase/2.8.x.x/sample_types.xml::4::csteele
-- +goose Up
-- +goose StatementBegin
-- add immunohistochemistry tests to post mortem
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Pan Keratin' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'AMACR (p504 s)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'BCL 2' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'BCL 6' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'BerEp4' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Calponin' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Calretinin' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD10' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD15' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD20' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD22' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD 3' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD30' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD34' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD45' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD 5' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD56' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD7' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD79a' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CD99 (O13)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-CDX-2 (EPR2764Y)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Chromogranin A' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Cytokeratin 20' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Cytokeratin 5/6' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Cytokeratin 7' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Cyclin D1 (SP4-R)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Desmin' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'DOG1 (SP31)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-E-Cadherin' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-EMA (E29)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-ER' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Gata 3' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Glial Fibrillary Acidic Protein' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-hepatocyte Specific Antigen (Hep Par-1)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Her2 Dual ISH' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-HER2' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-melanosome (HMB45)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Inhibin' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Ki67' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-MUC2' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-MUM1' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Myogenin (F5D)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Napsin A (MRQ-60)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'CINtec® p16 Histology' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-p40 (BC28)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'P 53' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-p63 (4A4)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Pax 5' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Pax 8' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-PR' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-S100' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Actin Smooth Muscle' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Synaptophysin (SP11)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Thyroid Transcription Factor' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Thyroglobulin (2H11+6E1)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Wilms'' tumor 1 protein (WT1)' ) ) ON CONFLICT DO NOTHING;
INSERT INTO clinlims.sampletype_test (id, sample_type_id, test_id) VALUES ( nextval( 'sample_type_test_seq' ) ,  ( select id from clinlims.type_of_sample where description = 'Tissue post mortem' ) ,  ( select id from clinlims.test where description = 'Anti-Vimentin' ) ) ON CONFLICT DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.8.x.x/sample_types.xml::4::csteele
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
