-- source: liquibase liquibase/2.8.x.x/notifications.xml::create_notifications_table::clinlims
-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS notifications (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP WITHOUT TIME ZONE, message VARCHAR(255) NOT NULL, user_id numeric(10, 0) NOT NULL, CONSTRAINT notifications_pkey PRIMARY KEY (id));
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES system_user (id);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.8.x.x/notifications.xml::create_notifications_table::clinlims
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
