-- source: liquibase liquibase/2.8.x.x/notification_subscriptions.xml::create_notification_subscriptions_table::clinlims
-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS notification_subscriptions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pf_endpoint TEXT NOT NULL, pf_p256dh TEXT NOT NULL, pf_auth TEXT NOT NULL, user_id numeric(10, 0) NOT NULL, CONSTRAINT notification_subscriptions_pkey PRIMARY KEY (id));
ALTER TABLE notification_subscriptions ADD CONSTRAINT fk_notification_subscriptions_user_id FOREIGN KEY (user_id) REFERENCES system_user (id);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/2.8.x.x/notification_subscriptions.xml::create_notification_subscriptions_table::clinlims
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
