-- source: liquibase liquibase/3.2.x.x/sample-management.xml::sample-mgmt-004-create-aliquot-relationship::dev-team
-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS sample_item_aliquot_relationship (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_sample_item_id numeric(10, 0) NOT NULL, child_sample_item_id numeric(10, 0) NOT NULL, sequence_number INTEGER NOT NULL, quantity_transferred DECIMAL(10, 3) NOT NULL, fhir_uuid UUID, notes VARCHAR(1000), lastupdated TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT sample_item_aliquot_relationship_pkey PRIMARY KEY (id), UNIQUE (fhir_uuid));
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS sample_item_aliquot_relationship;
-- +goose StatementEnd
