-- source: liquibase liquibase/3.3.x.x/026-patient-merge-create-audit-table.xml::patient-merge-001-create-audit-table::patient-merge-backend
-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS patient_merge_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, primary_patient_id BIGINT NOT NULL, merged_patient_id BIGINT NOT NULL, merge_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, performed_by_user_id BIGINT NOT NULL, reason TEXT NOT NULL, data_summary JSONB, last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), sys_user_id BIGINT, CONSTRAINT patient_merge_audit_pkey PRIMARY KEY (id));
ALTER TABLE patient_merge_audit ADD CONSTRAINT fk_pma_primary_patient FOREIGN KEY (primary_patient_id) REFERENCES patient (id) ON DELETE RESTRICT;
ALTER TABLE patient_merge_audit ADD CONSTRAINT fk_pma_merged_patient FOREIGN KEY (merged_patient_id) REFERENCES patient (id) ON DELETE RESTRICT;
ALTER TABLE patient_merge_audit ADD CONSTRAINT fk_pma_performed_by FOREIGN KEY (performed_by_user_id) REFERENCES system_user (id) ON DELETE RESTRICT;
ALTER TABLE patient_merge_audit ADD CONSTRAINT fk_pma_sys_user FOREIGN KEY (sys_user_id) REFERENCES system_user (id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_pma_primary_patient ON patient_merge_audit(primary_patient_id);
CREATE INDEX IF NOT EXISTS idx_pma_merged_patient ON patient_merge_audit(merged_patient_id);
CREATE INDEX IF NOT EXISTS idx_pma_merge_date ON patient_merge_audit(merge_date);
CREATE INDEX IF NOT EXISTS idx_pma_performed_by ON patient_merge_audit(performed_by_user_id);
CREATE INDEX IF NOT EXISTS idx_pma_data_summary ON patient_merge_audit USING gin(data_summary);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/3.3.x.x/026-patient-merge-create-audit-table.xml::patient-merge-001-create-audit-table::patient-merge-backend
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
