-- source: liquibase liquibase/3.4.14.x/002-create-analyzer-file-upload.xml::014-002-create-analyzer-file-upload::openelis
-- +goose Up
-- +goose StatementBegin
-- Create analyzer_file_upload table for file upload/import audit trail
CREATE TABLE IF NOT EXISTS analyzer_file_upload (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, analyzer_id INTEGER NOT NULL, filename VARCHAR(255) NOT NULL, file_hash_sha256 VARCHAR(64) NOT NULL, file_size BIGINT, status VARCHAR(20) DEFAULT 'PENDING' NOT NULL, result_count INTEGER, error_message TEXT, uploaded_by numeric(10, 0) NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, completed_at TIMESTAMP WITHOUT TIME ZONE, last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT analyzer_file_upload_pkey PRIMARY KEY (id), CONSTRAINT fk_analyzer_file_upload_analyzer FOREIGN KEY (analyzer_id) REFERENCES analyzer(id), CONSTRAINT fk_analyzer_file_upload_user FOREIGN KEY (uploaded_by) REFERENCES system_user(id));
CREATE INDEX IF NOT EXISTS idx_analyzer_file_upload_analyzer_id ON analyzer_file_upload(analyzer_id);
CREATE INDEX IF NOT EXISTS idx_analyzer_file_upload_created_at ON analyzer_file_upload(created_at);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/3.4.14.x/002-create-analyzer-file-upload.xml::014-002-create-analyzer-file-upload::openelis
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
