-- source: liquibase liquibase/3.4.14.x/003-create-analyzer-run.xml::014-003-create-analyzer-run::openelis
-- +goose Up
-- +goose StatementBegin
-- Create analyzer_run table for import batch and custom preview data
CREATE TABLE IF NOT EXISTS analyzer_run (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, analyzer_file_upload_id BIGINT NOT NULL, plugin_id VARCHAR(100), custom_preview_data JSONB, created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT analyzer_run_pkey PRIMARY KEY (id), CONSTRAINT fk_analyzer_run_upload FOREIGN KEY (analyzer_file_upload_id) REFERENCES analyzer_file_upload(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_analyzer_run_upload_id ON analyzer_run(analyzer_file_upload_id);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/3.4.14.x/003-create-analyzer-run.xml::014-003-create-analyzer-run::openelis
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
