-- source: liquibase liquibase/3.5.x.x/002-nce-enhancement.xml::nce-004-create-nce-attachment::reagan-meant
-- +goose Up
-- +goose StatementBegin
-- Create nce_attachment table for file attachments
CREATE TABLE IF NOT EXISTS clinlims.nce_attachment (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, nce_id INTEGER NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, file_type VARCHAR(100), file_size BIGINT, uploaded_by INTEGER, uploaded_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT nce_attachment_pkey PRIMARY KEY (id));
ALTER TABLE clinlims.nce_attachment ADD CONSTRAINT fk_nce_attachment_nce FOREIGN KEY (nce_id) REFERENCES clinlims.nc_event (id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_nce_attachment_nce_id ON clinlims.nce_attachment(nce_id);
CREATE SEQUENCE  IF NOT EXISTS clinlims.nce_attachment_seq START WITH 1 INCREMENT BY 1;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/3.5.x.x/002-nce-enhancement.xml::nce-004-create-nce-attachment::reagan-meant
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
