-- source: liquibase liquibase/3.5.x.x/002-nce-enhancement.xml::nce-018-create-nce-history::reagan-meant
-- +goose Up
-- +goose StatementBegin
-- Create nce_history table for NCE audit tracking
CREATE TABLE IF NOT EXISTS clinlims.nce_history (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, nce_id INTEGER NOT NULL, activity VARCHAR(100) NOT NULL, description TEXT, old_value TEXT, new_value TEXT, timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, user_id INTEGER, last_updated TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT nce_history_pkey PRIMARY KEY (id));
ALTER TABLE clinlims.nce_history ADD CONSTRAINT fk_nce_history_nce FOREIGN KEY (nce_id) REFERENCES clinlims.nc_event (id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_nce_history_nce_id ON clinlims.nce_history(nce_id);
CREATE INDEX IF NOT EXISTS idx_nce_history_timestamp ON clinlims.nce_history(timestamp);
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/3.5.x.x/002-nce-enhancement.xml::nce-018-create-nce-history::reagan-meant
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
