-- source: liquibase liquibase/3.5.x.x/order-attachment.xml::order-attachment-001-create-table::mozzy
-- +goose Up
-- +goose StatementBegin
-- Create order_attachment table for file attachments on orders (samples)
CREATE TABLE IF NOT EXISTS clinlims.order_attachment (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, sample_id numeric(10, 0) NOT NULL, original_file_name VARCHAR(255) NOT NULL, file_type VARCHAR(100), file_size_bytes BIGINT, file_content BYTEA NOT NULL, uploaded_by INTEGER, uploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, is_deleted BOOLEAN DEFAULT FALSE NOT NULL, last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT order_attachment_pkey PRIMARY KEY (id));
ALTER TABLE clinlims.order_attachment ADD CONSTRAINT fk_order_attachment_sample FOREIGN KEY (sample_id) REFERENCES clinlims.sample (id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_attachment_sample_id ON clinlims.order_attachment(sample_id);
CREATE SEQUENCE  IF NOT EXISTS clinlims.order_attachment_seq START WITH 1 INCREMENT BY 1;
-- +goose StatementEnd

-- +goose Down
-- TODO: no safe auto-generated rollback for this changeset.
-- Liquibase source: liquibase/3.5.x.x/order-attachment.xml::order-attachment-001-create-table::mozzy
-- Hand-write if this migration must be reversible; see
-- migration/liquibase-to-goose-plan.md sec 7 (Risk items).
