// AUTO-GENERATED by tools/extract-endpoints.mjs — do not edit by hand.
export const GET_ENDPOINTS: string[] = [
  "provider/search",
  "rest/accession-results",
  "rest/AccessionValidation",
  "rest/alert-notification-config/",
  "rest/alerts/",
  "rest/alerts/count",
  "rest/alerts/dashboard",
  "rest/alerts/dashboard/summary",
  "rest/AllTestsForSampleTypeProvider",
  "rest/analysis-status-types",
  "rest/AnalyzerTestName",
  "rest/AnalyzerTestNameMenu",
  "rest/AuditTrailReport",
  "rest/AuditTrailReport/exportCsv",
  "rest/AuditTrailReport/exportPdf",
  "rest/BatchTestReassignment",
  "rest/calendar/holidays",
  "rest/calendar/holidays/export",
  "rest/calendar/weekends",
  "rest/CancelAnalyzerTestName",
  "rest/CancelDictionary",
  "rest/CancelMenuStatementConfig",
  "rest/CancelNonConformityConfiguration",
  "rest/CancelOrganization",
  "rest/CancelPatientConfiguration",
  "rest/CancelPrintedReportsConfiguration",
  "rest/CancelResultConfiguration",
  "rest/CancelSampleEntryConfig",
  "rest/CancelSiteInformation",
  "rest/CancelValidationConfiguration",
  "rest/CancelWorkplanConfiguration",
  "rest/coldstorage/audit-trail/",
  "rest/coldstorage/reports/excursions",
  "rest/configuration-properties",
  "rest/DataExportStatus",
  "rest/DeleteMenuStatementConfig",
  "rest/DeleteNonConformityConfiguration",
  "rest/DeletePatientConfiguration",
  "rest/DeletePrintedReportsConfiguration",
  "rest/DeleteResultConfiguration",
  "rest/DeleteSiteInformation",
  "rest/DeleteWorkplanConfiguration",
  "rest/departments-for-site",
  "rest/Dictionary",
  "rest/dictionary-categories",
  "rest/DictionaryMenu",
  "rest/ElectronicOrders",
  "rest/EntityNamesProvider",
  "rest/eqa/distributions",
  "rest/eqa/eligible-organizations",
  "rest/eqa/my-programs/",
  "rest/eqa/my-programs/providers",
  "rest/eqa/orders/",
  "rest/eqa/orders/summary",
  "rest/eqa/programs/",
  "rest/esig/admin/certifications",
  "rest/esig/enabled",
  "rest/esig/signatures",
  "rest/ExternalConnection",
  "rest/ExternalConnectionMenu",
  "rest/GenericSampleOrder",
  "rest/getPendingAnalysisForTestProvider",
  "rest/inventory-storage-locations/",
  "rest/inventory-storage-locations/top-level",
  "rest/inventory/items/",
  "rest/inventory/items/all",
  "rest/inventory/items/low-stock",
  "rest/inventory/items/search",
  "rest/inventory/items/types",
  "rest/inventory/lots/",
  "rest/inventory/lots/expired",
  "rest/inventory/lots/expiring",
  "rest/inventory/management/alerts",
  "rest/inventory/management/check-availability",
  "rest/inventory/transactions/date-range",
  "rest/inventory/transactions/reference",
  "rest/labUnit/config",
  "rest/ListPlugins",
  "rest/localizations/",
  "rest/localizations/stats",
  "rest/LogbookResults",
  "rest/math-functions",
  "rest/menu",
  "rest/MenuStatementConfig",
  "rest/MenuStatementConfigMenu",
  "rest/MethodCreate",
  "rest/MethodRenameEntry",
  "rest/nce/categories",
  "rest/nce/dashboard",
  "rest/nce/generate-number",
  "rest/nce/users",
  "rest/NCECorrectiveAction",
  "rest/NextPreviousDictionary",
  "rest/NextPreviousMenuStatementConfig",
  "rest/NextPreviousNonConformityConfiguration",
  "rest/NextPreviousOrganization",
  "rest/NextPreviousPatientConfiguration",
  "rest/NextPreviousPrintedReportsConfiguration",
  "rest/NextPreviousResultConfiguration",
  "rest/NextPreviousSampleEntryConfig",
  "rest/NextPreviousSiteInformation",
  "rest/NextPreviousValidationConfiguration",
  "rest/NextPreviousWorkplanConfiguration",
  "rest/nonconformevents",
  "rest/nonconformingcorrectiveaction",
  "rest/NonConformityConfiguration",
  "rest/NonConformityConfigurationMenu",
  "rest/notebook/auditTrail",
  "rest/notebook/dashboard/entries",
  "rest/notebook/dashboard/metrics",
  "rest/notebook/dashboard/notebooks",
  "rest/notebook/list",
  "rest/notebook/notebooksamples",
  "rest/notebook/questionnaires",
  "rest/notebook/samples",
  "rest/open-configuration-properties",
  "rest/order/dashboard",
  "rest/order/search",
  "rest/Organization",
  "rest/organization-list",
  "rest/organization/generate-site-code",
  "rest/organization/search",
  "rest/organization/types",
  "rest/OrganizationExport",
  "rest/OrganizationMenu",
  "rest/PanelCreate",
  "rest/PanelOrder",
  "rest/PanelRenameEntry",
  "rest/PanelTestAssign",
  "rest/patientByLabNumer",
  "rest/PatientConfiguration",
  "rest/PatientConfigurationMenu",
  "rest/practitioner",
  "rest/PrintedReportsConfiguration",
  "rest/PrintedReportsConfigurationMenu",
  "rest/projects",
  "rest/ProviderMenu",
  "rest/ReferredOutTests",
  "rest/reflexrule-options",
  "rest/reflexrules",
  "rest/reportnonconformingevent",
  "rest/reports/tat/detail",
  "rest/reports/tat/export",
  "rest/reports/tat/summary",
  "rest/reports/tat/trend",
  "rest/result-tree",
  "rest/ResultConfiguration",
  "rest/ResultConfigurationMenu",
  "rest/ResultReportingConfiguration",
  "rest/ResultSelectListAdd",
  "rest/sample-item-status-types",
  "rest/sample-status-types",
  "rest/sample-type-tests",
  "rest/SampleBatchEntrySetup",
  "rest/SampleEdit",
  "rest/SampleEntryConfig",
  "rest/SampleEntryConfigMenu",
  "rest/SamplePatientEntry",
  "rest/SampleTypeCreate",
  "rest/SampleTypeOrder",
  "rest/SampleTypeRenameEntry",
  "rest/SampleTypeTestAssign",
  "rest/SearchExternalConnectionMenu",
  "rest/SearchOrganizationMenu",
  "rest/SearchProviderMenu",
  "rest/SearchUnifiedSystemUserMenu",
  "rest/SelectListRenameEntry",
  "rest/server-time",
  "rest/shipping-box/",
  "rest/shipping-box/box-label-prefix",
  "rest/shipping-box/fhir-mapping-config",
  "rest/shipping-box/generate-box-number",
  "rest/shipping-box/site-organization-uuid",
  "rest/shipping-box/statistics",
  "rest/site-branding/",
  "rest/SiteInformation",
  "rest/SiteInformationMenu",
  "rest/supportedlocales/",
  "rest/supportedlocales/active",
  "rest/supportedlocales/fallback",
  "rest/systemAuditEvents",
  "rest/systemAuditEvents/entityTypes",
  "rest/systemAuditEvents/export",
  "rest/systemAuditEvents/exportPdf",
  "rest/systemroles",
  "rest/systemroles-testsections",
  "rest/test-calculations",
  "rest/test-catalog/dictionary",
  "rest/test-catalog/group/summary",
  "rest/test-catalog/lab-units",
  "rest/test-catalog/panels",
  "rest/test-catalog/sample-types",
  "rest/test-catalog/tests",
  "rest/test-display-beans",
  "rest/test-display-beans-map",
  "rest/test-list",
  "rest/test-result-tree",
  "rest/test-sample-types",
  "rest/TestActivation",
  "rest/TestAdd",
  "rest/TestCatalog",
  "rest/TestModifyEntry",
  "rest/TestNamesProvider",
  "rest/TestNotificationConfig",
  "rest/TestNotificationConfig/raw/list",
  "rest/TestNotificationConfigMenu",
  "rest/TestOrderability",
  "rest/TestRenameEntry",
  "rest/tests-by-sample",
  "rest/TestSectionCreate",
  "rest/TestSectionOrder",
  "rest/TestSectionRenameEntry",
  "rest/TestSectionTestAssign",
  "rest/trendsprojects",
  "rest/unassigned-sample/",
  "rest/unassigned-sample/items",
  "rest/unassigned-sample/items/search",
  "rest/UnifiedSystemUser",
  "rest/UnifiedSystemUserMenu",
  "rest/uom",
  "rest/UomCreate",
  "rest/UomRenameEntry",
  "rest/user-programs",
  "rest/user-sample-types",
  "rest/users",
  "rest/ValidationConfiguration",
  "rest/ValidationConfigurationMenu",
  "rest/viewNonConformEvents",
  "rest/WorkPlanByPanel",
  "rest/WorkPlanByPriority",
  "rest/WorkPlanByTest",
  "rest/WorkPlanByTestSection",
  "rest/WorkplanConfiguration",
  "rest/WorkplanConfigurationMenu"
];

export const GET_ENDPOINTS_WITH_PARAMS: string[] = [
  "Provider/Person/{id}",
  "Provider/raw/{id}",
  "rest/admin/menu/{elementId}",
  "rest/alerts/{id}",
  "rest/api/tests/{id}/labelConfig",
  "rest/box-sample/{id}",
  "rest/box-sample/by-box/{shippingBoxId}",
  "rest/box-sample/by-box/{shippingBoxId}/status/{status}",
  "rest/box-sample/by-sample/{sampleId}",
  "rest/box-sample/check-sample/{sampleId}",
  "rest/box-sample/count-by-box/{shippingBoxId}",
  "rest/box-sample/items/by-box/{shippingBoxId}",
  "rest/box-sample/items/check/{sampleItemId}",
  "rest/box-sample/items/count-by-box/{shippingBoxId}",
  "rest/DataExportStatus/{taskId}/attempts",
  "rest/dictionary/category/{categoryName}",
  "rest/displayList/{listType}",
  "rest/eqa/distributions/{distributionId}/results",
  "rest/eqa/distributions/{distributionId}/statistics",
  "rest/eqa/distributions/{id}",
  "rest/eqa/my-programs/{id}",
  "rest/eqa/programs/{id}",
  "rest/eqa/programs/{id}/tests",
  "rest/eqa/programs/{programId}/enrollments",
  "rest/esig/certified/{username}",
  "rest/esig/session-status/{username}",
  "rest/inventory-storage-locations/{id}",
  "rest/inventory-storage-locations/{id}/has-active-lots",
  "rest/inventory-storage-locations/{id}/path",
  "rest/inventory-storage-locations/{parentId}/children",
  "rest/inventory-storage-locations/code/{code}",
  "rest/inventory-storage-locations/type/{locationType}",
  "rest/inventory/items/{id}",
  "rest/inventory/items/{id}/stock",
  "rest/inventory/items/category/{category}",
  "rest/inventory/items/type/{itemType}",
  "rest/inventory/lots/{id}",
  "rest/inventory/lots/item/{itemId}",
  "rest/inventory/lots/item/{itemId}/available",
  "rest/inventory/lots/item/{itemId}/total-quantity",
  "rest/inventory/lots/location/{locationId}",
  "rest/inventory/lots/lot-number/{lotNumber}",
  "rest/inventory/transactions/{id}",
  "rest/inventory/transactions/lot/{lotId}",
  "rest/inventory/transactions/type/{transactionType}",
  "rest/inventory/usage/{id}",
  "rest/inventory/usage/analysis/{analysisId}",
  "rest/inventory/usage/item/{itemId}",
  "rest/inventory/usage/lot/{lotId}",
  "rest/inventory/usage/test-result/{testResultId}",
  "rest/localizations/{id}",
  "rest/localizations/export/{locale}",
  "rest/localizations/missing/{locale}",
  "rest/menu/{elementId}",
  "rest/methods-for-test/{testId}",
  "rest/nce/attachments/{attachmentId}/download",
  "rest/notebook/dashboard/entries/{noteBookId}",
  "rest/notebook/view/{noteBookId}",
  "rest/order/{accessionNumber}/attachments",
  "rest/order/attachments/{attachmentId}/download",
  "rest/order/attachments/{attachmentId}/view",
  "rest/organization/{id}",
  "rest/paginatedDisplayList/{listType}",
  "rest/patient-id-documents/{patientId}",
  "rest/patient-id-documents/{patientId}/{documentId}/full",
  "rest/patient-photos/{id}/{isThumbnail}",
  "rest/patient/merge/details/{patientId}",
  "rest/sample-type-requests/sample/{sampleId}",
  "rest/sample-type-requests/sample/{sampleId}/pending",
  "rest/sample/all-by-accession/{accessionNumber}",
  "rest/sample/unassigned-by-accession/{accessionNumber}",
  "rest/shipping-box/{id}",
  "rest/shipping-box/{id}/label/pdf",
  "rest/shipping-box/{id}/manifest-data",
  "rest/shipping-box/{id}/manifest/pdf",
  "rest/shipping-box/by-box-id/{boxId}",
  "rest/shipping-box/by-facility/{facilityId}",
  "rest/shipping-box/by-state/{state}",
  "rest/site-branding/logo/{type}",
  "rest/supportedlocales/{id}",
  "rest/test-catalog/{testId}/alerts/",
  "rest/test-catalog/{testId}/alerts/roles",
  "rest/test-catalog/{testId}/reagents/",
  "rest/test-catalog/{testId}/reflex-calc/",
  "rest/test-catalog/{testId}/storage/history/",
  "rest/test-catalog/panels/{panelId}/test-order",
  "rest/test-catalog/sample-types/{sampleTypeId}/test-order",
  "rest/test-catalog/tests/{testId}",
  "rest/test-catalog/tests/{testId}/analyzers",
  "rest/test-catalog/tests/{testId}/basic-info",
  "rest/test-catalog/tests/{testId}/localization",
  "rest/test-catalog/tests/{testId}/loinc-integrity",
  "rest/test-catalog/tests/{testId}/panels",
  "rest/test-catalog/tests/{testId}/ranges",
  "rest/test-catalog/tests/{testId}/sample-results",
  "rest/test-catalog/tests/{testId}/siblings",
  "rest/test-catalog/tests/{testId}/storage",
  "rest/test-catalog/tests/{testId}/terminology",
  "rest/test/{testId}/methods/",
  "rest/unassigned-sample/by-facility/{facilityId}",
  "rest/unassigned-sample/count-by-facility/{facilityId}",
  "rest/user-test-sections/{roleName}",
  "rest/users/{roleName}"
];

// Full per-endpoint verb map (the "manipulation pattern").
export interface EndpointMethods { path: string; methods: string[]; }
export const ENDPOINT_METHODS: EndpointMethods[] = [
  {
    "path": "Provider/FhirUuid",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "Provider/Person/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "Provider/raw/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "provider/search",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/accession-results",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/AccessionValidation",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/activate-reflexrule/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/activate-test-calculation/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/admin/menu/{elementId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/alert-notification-config/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/alerts/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/alerts/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/alerts/{id}/acknowledge",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/alerts/{id}/resolve",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/alerts/count",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/alerts/dashboard",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/alerts/dashboard/summary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/AllTestsForSampleTypeProvider",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/analysis-status-types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/AnalyzerTestName",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/AnalyzerTestNameMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/api/tests/{id}/labelConfig",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/AuditTrailReport",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/AuditTrailReport/exportCsv",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/AuditTrailReport/exportPdf",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/BatchTestReassignment",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/{id}",
    "methods": [
      "DELETE",
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/{id}/reception-status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/box-sample/{id}/remove",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/by-box/{shippingBoxId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/by-box/{shippingBoxId}/status/{status}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/by-sample/{sampleId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/check-sample/{sampleId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/count-by-box/{shippingBoxId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/items",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/items/{id}",
    "methods": [
      "DELETE"
    ]
  },
  {
    "path": "rest/box-sample/items/{id}/reception-status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/box-sample/items/{id}/remove",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/items/by-box/{shippingBoxId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/items/check/{sampleItemId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/items/count-by-box/{shippingBoxId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/calendar/holidays",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/calendar/holidays/{id}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/calendar/holidays/export",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/calendar/holidays/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/calendar/weekends",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/CancelAnalyzerTestName",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelDictionary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelMenuStatementConfig",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelNonConformityConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelOrganization",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelPatientConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelPrintedReportsConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelResultConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelSampleEntryConfig",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelSiteInformation",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelValidationConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/CancelWorkplanConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/coldstorage/audit-trail/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/coldstorage/reports/excursions",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/configuration-properties",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DataExportStatus",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DataExportStatus/{taskId}/attempts",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DataExportStatus/{taskId}/trigger",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/deactivate-reflexrule/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/deactivate-test-calculation/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeactivateExternalConnection",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteAnalyzerTestName",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteDictionary",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteMenuStatementConfig",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DeleteNonConformityConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DeleteOrganization",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeletePatientConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DeletePrintedReportsConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DeleteProvider",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteResultConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DeleteSiteInformation",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DeleteUnifiedSystemUser",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteWorkplanConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/departments-for-site",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/Dictionary",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/dictionary-categories",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/dictionary/category/{categoryName}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/DictionaryMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/displayList/{listType}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ElectronicOrders",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/EntityNamesProvider",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/distributions",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/results",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/results/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/statistics",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/submit/{organizationId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/submit/{organizationId}/approve-late",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/distributions/{id}/barcodes",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{id}/status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/eligible-organizations",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/my-programs/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/my-programs/{id}",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/my-programs/providers",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/orders/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/orders/summary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/eqa/programs/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/programs/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/programs/{id}/tests",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/programs/{programId}/enrollments",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/programs/{programId}/enrollments/{enrollmentId}",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/esig/admin/certifications",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/esig/admin/certifications/{username}",
    "methods": [
      "DELETE"
    ]
  },
  {
    "path": "rest/esig/certified/{username}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/esig/certify",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/esig/enabled",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/esig/session-status/{username}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/esig/sign",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/esig/signatures",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ExternalConnection",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ExternalConnectionMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/GenericSampleOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/GenericSampleOrder/{accessionNumber}",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/GenericSampleOrder/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/GenericSampleOrder/validate",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/getPendingAnalysisForTestProvider",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{id}/deactivate",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{id}/has-active-lots",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{id}/path",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{parentId}/children",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/code/{code}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/top-level",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/type/{locationType}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/inventory/items/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/items/{id}/activate",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/items/{id}/deactivate",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/items/{id}/stock",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/all",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/category/{category}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/low-stock",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/search",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/type/{itemType}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/items/types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/adjust",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/dispose",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/open",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/qc-status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/expired",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/expiring",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/item/{itemId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/item/{itemId}/available",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/item/{itemId}/total-quantity",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/location/{locationId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/lot-number/{lotNumber}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/lots/process-expired",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/management/alerts",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/management/check-availability",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/management/consume",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/management/receive",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/transactions/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/transactions/date-range",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/transactions/lot/{lotId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/transactions/reference",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/transactions/type/{transactionType}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/usage/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/usage/analysis/{analysisId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/usage/item/{itemId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/usage/lot/{lotId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/inventory/usage/test-result/{testResultId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/labUnit/config",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ListPlugins",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/localizations/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/localizations/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/localizations/{id}/translations",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/localizations/{id}/translations/{locale}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/localizations/export/{locale}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/localizations/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/localizations/missing/{locale}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/localizations/stats",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/LogbookResults",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/logoUpload/",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/math-functions",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/menu",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/menu/{elementId}",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/MenuStatementConfig",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/MenuStatementConfigMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/MethodCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/MethodRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/methods-for-test/{testId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nce/assign",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/nce/attachments/{attachmentId}/download",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nce/categories",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nce/dashboard",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nce/generate-number",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nce/history",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/nce/users",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NCECorrectiveAction",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/NextPreviousDictionary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousMenuStatementConfig",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousNonConformityConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousOrganization",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousPatientConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousPrintedReportsConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousResultConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousSampleEntryConfig",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousSiteInformation",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousValidationConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NextPreviousWorkplanConfiguration",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nonconformevents",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/nonconformingcorrectiveaction",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/NonConformityConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/NonConformityConfigurationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/auditTrail",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/create",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/notebook/dashboard/entries",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/dashboard/entries/{noteBookId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/dashboard/metrics",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/dashboard/notebooks",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/list",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/notebooksamples",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/questionnaires",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/samples",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/notebook/update/{noteBookId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/notebook/updatestatus/{noteBookId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/notebook/view/{noteBookId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/open-configuration-properties",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/order/{accessionNumber}/attachments",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/order/attachments/{attachmentId}",
    "methods": [
      "DELETE"
    ]
  },
  {
    "path": "rest/order/attachments/{attachmentId}/download",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/order/attachments/{attachmentId}/view",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/order/dashboard",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/order/search",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/Organization",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/organization-list",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/organization/{id}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/organization/generate-site-code",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/organization/search",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/organization/types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/OrganizationExport",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/OrganizationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/paginatedDisplayList/{listType}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/PanelCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelTestAssign",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/patient-id-documents/{documentId}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/patient-id-documents/{patientId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/patient-id-documents/{patientId}/{documentId}/full",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/patient-photos/{id}/{isThumbnail}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/patient/merge/details/{patientId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/patient/merge/execute",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/patient/merge/validate",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/patientByLabNumer",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/PatientConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PatientConfigurationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/PatientManagement",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/practitioner",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/PrintedReportsConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PrintedReportsConfigurationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/PrintWorkplanReport",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/projects",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ProviderMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ReferredOutTests",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/reflexrule",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/reflexrule-options",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/reflexrules",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/reportnonconformingevent",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/reportnonconformingevent/with-attachments",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/ReportPrint",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/reports/tat/detail",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/reports/tat/export",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/reports/tat/summary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/reports/tat/trend",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/result-tree",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ResultConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ResultConfigurationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ResultReportingConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ResultSelectListAdd",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/sample-item-status-types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/sample-status-types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/sample-type-requests/",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/sample-type-requests/{requestId}/cancel",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/sample-type-requests/{requestId}/fulfill",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/sample-type-requests/sample/{sampleId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/sample-type-requests/sample/{sampleId}/pending",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/sample-type-tests",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/sample/all-by-accession/{accessionNumber}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/sample/unassigned-by-accession/{accessionNumber}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SampleBatchEntry",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SampleBatchEntrySetup",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SampleEdit",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleEntryConfig",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleEntryConfigMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SamplePatientEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SamplePatientEntryBatch",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeTestAssign",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SaveResultSelectList",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SearchExternalConnectionMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SearchOrganizationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SearchProviderMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SearchUnifiedSystemUserMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/SelectListRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/server-time",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/shipping-box/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/archive",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/label/pdf",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/manifest-data",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/manifest/pdf",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/state",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/box-label-prefix",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/by-box-id/{boxId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/by-facility/{facilityId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/by-state/{state}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/fhir-mapping-config",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/generate-box-number",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/shipping-box/import-from-fhir",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/shipping-box/site-organization-uuid",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/statistics",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/site-branding/",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/site-branding/logo/{type}",
    "methods": [
      "DELETE",
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/site-branding/reset",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SiteInformation",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SiteInformationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/supportedlocales/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/supportedlocales/{id}",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/supportedlocales/{id}/setFallback",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/supportedlocales/active",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/supportedlocales/fallback",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/systemAuditEvents",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/systemAuditEvents/entityTypes",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/systemAuditEvents/export",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/systemAuditEvents/exportPdf",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/systemroles",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/systemroles-testsections",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-calculation",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-calculations",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/alerts/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/alerts/{ruleId}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/alerts/roles",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/reagents/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/reagents/{reagentId}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/reflex-calc/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/storage/history/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/dictionary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/group/ranges",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/group/storage",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/group/summary",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/lab-units",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/panels",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/panels/{panelId}/test-order",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/sample-types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/sample-types/{sampleTypeId}/test-order",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/activate",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/analyzers",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/basic-info",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/localization",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/loinc-integrity",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/panels",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/ranges",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/sample-results",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/sample-results/copy-from/{sourceId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/siblings",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/storage",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/terminology",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-display-beans",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-display-beans-map",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-list",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-result-tree",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test-sample-types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/{id}",
    "methods": [
      "DELETE",
      "PATCH"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/copyFrom/{sourceTestId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/inline-create",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/TestActivation",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestAdd",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestCatalog",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/TestModifyEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestNamesProvider",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/TestNotificationConfig",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestNotificationConfig/raw/list",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/TestNotificationConfigMenu",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestOrderability",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/tests-by-sample",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/TestSectionCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionTestAssign",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/trendsprojects",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/unassigned-sample/",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/unassigned-sample/{referralId}/assign-to-box",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/unassigned-sample/{referralId}/cancel",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/unassigned-sample/{referralId}/mark-lost",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/unassigned-sample/by-facility/{facilityId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/unassigned-sample/count-by-facility/{facilityId}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/unassigned-sample/items",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/unassigned-sample/items/search",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/UnifiedSystemUser",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/UnifiedSystemUserMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/uom",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/UomCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/UomRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/user-programs",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/user-sample-types",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/user-test-sections/{roleName}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/users",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/users/{roleName}",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/ValidationConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ValidationConfigurationMenu",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/viewNonConformEvents",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/WorkPlanByPanel",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/WorkPlanByPriority",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/WorkPlanByTest",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/WorkPlanByTestSection",
    "methods": [
      "GET"
    ]
  },
  {
    "path": "rest/WorkplanConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/WorkplanConfigurationMenu",
    "methods": [
      "GET"
    ]
  }
];

// Write endpoints (state-changing) — every one must be CSRF-protected.
export const WRITE_ENDPOINTS: EndpointMethods[] = [
  {
    "path": "Provider/FhirUuid",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/AccessionValidation",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/activate-reflexrule/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/activate-test-calculation/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/alert-notification-config/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/alerts/{id}/acknowledge",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/alerts/{id}/resolve",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/AnalyzerTestName",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/api/tests/{id}/labelConfig",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/BatchTestReassignment",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/{id}",
    "methods": [
      "DELETE",
      "GET"
    ]
  },
  {
    "path": "rest/box-sample/{id}/reception-status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/box-sample/{id}/remove",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/items",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/box-sample/items/{id}",
    "methods": [
      "DELETE"
    ]
  },
  {
    "path": "rest/box-sample/items/{id}/reception-status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/box-sample/items/{id}/remove",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/calendar/holidays",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/calendar/holidays/{id}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/calendar/holidays/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/calendar/weekends",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/DataExportStatus/{taskId}/trigger",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/deactivate-reflexrule/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/deactivate-test-calculation/{id}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeactivateExternalConnection",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteAnalyzerTestName",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteDictionary",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteOrganization",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteProvider",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/DeleteUnifiedSystemUser",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/Dictionary",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/results",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/results/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/submit/{organizationId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{distributionId}/submit/{organizationId}/approve-late",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{id}/barcodes",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/eqa/distributions/{id}/status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/my-programs/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/my-programs/{id}",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/programs/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/programs/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/programs/{id}/tests",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/eqa/programs/{programId}/enrollments",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/eqa/programs/{programId}/enrollments/{enrollmentId}",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/esig/admin/certifications/{username}",
    "methods": [
      "DELETE"
    ]
  },
  {
    "path": "rest/esig/certify",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/esig/sign",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/ExternalConnection",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/GenericSampleOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/GenericSampleOrder/{accessionNumber}",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/GenericSampleOrder/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/GenericSampleOrder/validate",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/inventory-storage-locations/{id}/deactivate",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/items/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/inventory/items/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/items/{id}/activate",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/items/{id}/deactivate",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/adjust",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/dispose",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/open",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/qc-status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/{id}/status",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/inventory/lots/process-expired",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/management/consume",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/inventory/management/receive",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/localizations/{id}/translations",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/localizations/{id}/translations/{locale}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/localizations/import",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/LogbookResults",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/logoUpload/",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/menu",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/menu/{elementId}",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/MenuStatementConfig",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/MethodCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/MethodRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/nce/assign",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/nce/history",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/NCECorrectiveAction",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/NonConformityConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/notebook/create",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/notebook/update/{noteBookId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/notebook/updatestatus/{noteBookId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/order/{accessionNumber}/attachments",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/order/attachments/{attachmentId}",
    "methods": [
      "DELETE"
    ]
  },
  {
    "path": "rest/Organization",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PanelTestAssign",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/patient-id-documents/{documentId}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/patient/merge/execute",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/patient/merge/validate",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/PatientConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PatientManagement",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/PrintedReportsConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/PrintWorkplanReport",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/reflexrule",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/reportnonconformingevent",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/reportnonconformingevent/with-attachments",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/ReportPrint",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/ResultConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ResultReportingConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ResultSelectListAdd",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/sample-type-requests/",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/sample-type-requests/{requestId}/cancel",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/sample-type-requests/{requestId}/fulfill",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/SampleBatchEntry",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SampleEdit",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleEntryConfig",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SamplePatientEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SamplePatientEntryBatch",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SampleTypeTestAssign",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/SaveResultSelectList",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SelectListRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/shipping-box/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/shipping-box/{id}",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/archive",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/{id}/state",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/box-label-prefix",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/fhir-mapping-config",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/shipping-box/import-from-fhir",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/shipping-box/site-organization-uuid",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/site-branding/",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/site-branding/logo/{type}",
    "methods": [
      "DELETE",
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/site-branding/reset",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/SiteInformation",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/supportedlocales/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/supportedlocales/{id}",
    "methods": [
      "DELETE",
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/supportedlocales/{id}/setFallback",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-calculation",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/alerts/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/alerts/{ruleId}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/reagents/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/{testId}/reagents/{reagentId}",
    "methods": [
      "DELETE",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/group/ranges",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/group/storage",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/panels",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/sample-types/{sampleTypeId}/test-order",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/activate",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/basic-info",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/panels",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/ranges",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/sample-results",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/sample-results/copy-from/{sourceId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/storage",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test-catalog/tests/{testId}/terminology",
    "methods": [
      "GET",
      "PUT"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/{id}",
    "methods": [
      "DELETE",
      "PATCH"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/copyFrom/{sourceTestId}",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/test/{testId}/methods/inline-create",
    "methods": [
      "POST"
    ]
  },
  {
    "path": "rest/TestActivation",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestAdd",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestModifyEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestNotificationConfig",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestNotificationConfigMenu",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestOrderability",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionOrder",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/TestSectionTestAssign",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/unassigned-sample/{referralId}/assign-to-box",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/unassigned-sample/{referralId}/cancel",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/unassigned-sample/{referralId}/mark-lost",
    "methods": [
      "PUT"
    ]
  },
  {
    "path": "rest/UnifiedSystemUser",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/uom",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/UomCreate",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/UomRenameEntry",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/ValidationConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/viewNonConformEvents",
    "methods": [
      "GET",
      "POST"
    ]
  },
  {
    "path": "rest/WorkplanConfiguration",
    "methods": [
      "GET",
      "POST"
    ]
  }
];
